/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaces;

import gerenciador.FuncoesUteis;
import gerenciador.GerenciadorInterfaceGrafica;
import java.awt.Color;
import javax.swing.JOptionPane;
import modelo.Cliente;
import org.hibernate.HibernateException;

/**
 *
 * @author CONEXOS
 */
public class CadastroCliente extends javax.swing.JDialog {

    private GerenciadorInterfaceGrafica gerenciadorInterfaceGrafica;
    private Cliente clienteSelecionado;

    /**
     * Creates new form Açai
     *
     * @param parent
     * @param modal
     * @param gerenciadoInterfaceGrafica
     */
    public CadastroCliente(java.awt.Frame parent, boolean modal, GerenciadorInterfaceGrafica gerenciadoInterfaceGrafica) {
        super(parent, modal);
        this.gerenciadorInterfaceGrafica = gerenciadoInterfaceGrafica;
        clienteSelecionado = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpSexo = new javax.swing.ButtonGroup();
        mnuPopUp = new javax.swing.JPopupMenu();
        mnuInserir = new javax.swing.JMenuItem();
        mnuAlterar = new javax.swing.JMenuItem();
        mnuExcluir = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtEndereço = new javax.swing.JTextField();
        pnlSexo = new javax.swing.JPanel();
        rbtnMasculino = new javax.swing.JRadioButton();
        rbtnFeminino = new javax.swing.JRadioButton();
        btnPesquisar = new javax.swing.JButton();
        lblNumero = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        mnuInserir.setText("Inserir");
        mnuPopUp.add(mnuInserir);

        mnuAlterar.setText("Alterar");
        mnuPopUp.add(mnuAlterar);

        mnuExcluir.setText("Excluir");
        mnuPopUp.add(mnuExcluir);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));

        lblNome.setText("Nome");

        lblEndereco.setText("Endereço");

        pnlSexo.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));
        pnlSexo.setLayout(new java.awt.BorderLayout());

        grpSexo.add(rbtnMasculino);
        rbtnMasculino.setMnemonic('M');
        rbtnMasculino.setText("Masculino");
        pnlSexo.add(rbtnMasculino, java.awt.BorderLayout.CENTER);

        grpSexo.add(rbtnFeminino);
        rbtnFeminino.setMnemonic('F');
        rbtnFeminino.setSelected(true);
        rbtnFeminino.setText("Feminino");
        pnlSexo.add(rbtnFeminino, java.awt.BorderLayout.PAGE_START);

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        lblNumero.setText("Nº");

        lblBairro.setText("Bairro");

        lblCidade.setText("Cidade");

        lblCelular.setText("Celular");

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCelular)
                    .addComponent(lblCidade)
                    .addComponent(lblBairro)
                    .addComponent(lblNumero)
                    .addComponent(lblEndereco)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBairro)
                    .addComponent(txtCidade)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnPesquisar))
                                .addComponent(txtEndereço))
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCelular))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome)
                            .addComponent(btnPesquisar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEndereco)
                            .addComponent(txtEndereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumero)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pnlSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCelular)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(btnNovo)
                .addGap(75, 75, 75)
                .addComponent(btnExcluir)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnExcluir))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Clientes"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sexo", "Endereço", "Número", "Bairro", "Cidade", "Celular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        if (validarCampos()) {
            //INSERIR no banco
            String nome = txtNome.getText();
            String endereco = txtEndereço.getText();
            int numero = Integer.parseInt(txtNumero.getText());
            String bairro = txtBairro.getText();
            String cidade = txtCidade.getText();
            String celular = txtCelular.getText();
            char sexo = (char) grpSexo.getSelection().getMnemonic();

            try {
                if (clienteSelecionado == null) {
                    int id = gerenciadorInterfaceGrafica.getGerenciadorDominio().inserirCliente(nome, sexo, endereco,
                            numero, bairro, cidade, celular);

                    JOptionPane.showMessageDialog(this, "Cliente " + id + " inserido com sucesso!");
                } else {
                    gerenciadorInterfaceGrafica.getGerenciadorDominio().alterarCliente(clienteSelecionado, nome, sexo, endereco,
                            numero, bairro, cidade, celular);

                    JOptionPane.showMessageDialog(this, "Cliente " + clienteSelecionado.getId() + " alterado com sucesso!");
                }

                gerenciadorInterfaceGrafica.carregarTabelaCliente(tblClientes, Cliente.class);
                limparCampos();
                nomeBotao();
            } catch (HibernateException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao inserir cliente.");
            }
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int linha = tblClientes.getSelectedRow();
        try {
            if (linha >= 0) {
                Cliente cliente = (Cliente) tblClientes.getValueAt(linha, 0);
                if (JOptionPane.showConfirmDialog(this, "Deseja excluir esse cliente?") == JOptionPane.YES_OPTION) {
                    gerenciadorInterfaceGrafica.excluirCliente(cliente);
                    gerenciadorInterfaceGrafica.carregarTabelaCliente(tblClientes, Cliente.class);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um cliente.");
            }
        } catch (HibernateException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir cliente. " + ex);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        limparCampos();
        clienteSelecionado = gerenciadorInterfaceGrafica.abrirJanelaPesquisarCliente();
        gerenciadorInterfaceGrafica.carregarTabelaCliente(tblClientes, Cliente.class);
        nomeBotao();
        preencherCampos();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        gerenciadorInterfaceGrafica.carregarTabelaCliente(tblClientes, Cliente.class);
        nomeBotao();
    }//GEN-LAST:event_formComponentShown

    private boolean validarCampos() {
        String msgErro = "";
        FuncoesUteis.voltarCor(lblNome);
        FuncoesUteis.voltarCor(lblEndereco);
        FuncoesUteis.voltarCor(lblNumero);
        FuncoesUteis.voltarCor(lblBairro);
        FuncoesUteis.voltarCor(lblCidade);
        FuncoesUteis.voltarCor(lblCelular);

        if (txtNome.getText().isEmpty()) {
            msgErro = msgErro + "Digite seu NOME.\n";
            lblNome.setForeground(Color.red);
        }

        if (txtEndereço.getText().isEmpty()) {
            msgErro = msgErro + "Digite seu ENDEREÇO.\n";
            lblEndereco.setForeground(Color.red);
        }

        if (txtNumero.getText().isEmpty()) {
            msgErro = msgErro + "Digite seu NÚMERO.\n";
            lblNumero.setForeground(Color.red);
        } else {
            try {
                Integer.parseInt(txtNumero.getText());
            } catch (NumberFormatException e) {
                msgErro = msgErro + "Digite um NÚMERO válido.\n";
                lblNumero.setForeground(Color.red);
            }
        }

        if (txtBairro.getText().isEmpty()) {
            msgErro = msgErro + "Digite seu BAIRRO.\n";
            lblBairro.setForeground(Color.red);
        }

        if (txtCidade.getText().isEmpty()) {
            msgErro = msgErro + "Digite seu CIDADE.\n";
            lblCidade.setForeground(Color.red);
        }

        if (txtCelular.getText().isEmpty()) {
            msgErro = msgErro + "Digite seu CELULAR.\n";
            lblCelular.setForeground(Color.red);
        }

        if (msgErro.isEmpty()) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, msgErro, "Cadastro de Cliente", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private void preencherCampos() {
        if (clienteSelecionado != null) {
            txtNome.setText(clienteSelecionado.getNome());
            txtEndereço.setText(clienteSelecionado.getEndereco());
            txtNumero.setText(String.valueOf(clienteSelecionado.getNumero()));
            txtBairro.setText(clienteSelecionado.getBairro());
            txtCidade.setText(clienteSelecionado.getCidade());
            txtCelular.setText(clienteSelecionado.getCelular());
            if (clienteSelecionado.getSexo() == 'M') {
                rbtnMasculino.setSelected(true);
            } else {
                rbtnFeminino.setSelected(true);
            }
        }
    }

    private void nomeBotao() {
        if (clienteSelecionado == null) {
            btnNovo.setText("Novo");
        } else {
            btnNovo.setText("Alterar");
        }
    }

    private void limparCampos() {
        clienteSelecionado = null;
        txtNome.setText("");
        txtEndereço.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtCelular.setText("");
        rbtnFeminino.setSelected(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.ButtonGroup grpSexo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JMenuItem mnuAlterar;
    private javax.swing.JMenuItem mnuExcluir;
    private javax.swing.JMenuItem mnuInserir;
    private javax.swing.JPopupMenu mnuPopUp;
    private javax.swing.JPanel pnlSexo;
    private javax.swing.JRadioButton rbtnFeminino;
    private javax.swing.JRadioButton rbtnMasculino;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEndereço;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
