/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaces;

import gerenciador.FuncoesUteis;
import gerenciador.GerenciadorInterfaceGrafica;
import java.awt.Color;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Acai;
import modelo.Cliente;
import modelo.Tamanho;
import modelo.TamanhoAcai;
import org.hibernate.HibernateException;

/**
 *
 * @author CONEXOS
 */
public class CadastroPedidos extends javax.swing.JDialog {

    private GerenciadorInterfaceGrafica gerenciadorInterfaceGrafica;
    private Cliente clienteSelecionado;

    /**
     * Creates new form CadastroAcai
     *
     * @param parent
     * @param modal
     * @param gerenciadoInterfaceGrafica
     */
    public CadastroPedidos(java.awt.Frame parent, boolean modal, GerenciadorInterfaceGrafica gerenciadoInterfaceGrafica) {
        super(parent, modal);
        this.gerenciadorInterfaceGrafica = gerenciadoInterfaceGrafica;
        clienteSelecionado = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpEntrega = new javax.swing.ButtonGroup();
        mnuPopUp = new javax.swing.JPopupMenu();
        mnuInserir = new javax.swing.JMenuItem();
        mnuAlterar = new javax.swing.JMenuItem();
        mnuExcluir = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblAcai = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cbxMorango = new javax.swing.JCheckBox();
        cbxBanana = new javax.swing.JCheckBox();
        cbxCereja = new javax.swing.JCheckBox();
        txtNome = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        cmbAcai = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        cbxLeiteCondensado = new javax.swing.JCheckBox();
        cbxCoberturaMorango = new javax.swing.JCheckBox();
        cbxCoberturaChocolate = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        cbxLeitePo = new javax.swing.JCheckBox();
        cbxPacoca = new javax.swing.JCheckBox();
        cbxChocoball = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        rbtnSim = new javax.swing.JRadioButton();
        rbtnNao = new javax.swing.JRadioButton();
        txtPreço = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spnQtd = new javax.swing.JSpinner();
        btnNovo = new javax.swing.JButton();
        cmbTamanho = new javax.swing.JComboBox<>();
        lblTamanho = new javax.swing.JLabel();
        btnExcluirPedido = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();

        mnuInserir.setText("Inserir");
        mnuInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        mnuPopUp.add(mnuInserir);

        mnuAlterar.setText("Alterar");
        mnuPopUp.add(mnuAlterar);

        mnuExcluir.setText("Excluir");
        mnuExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPedidoActionPerformed(evt);
            }
        });
        mnuPopUp.add(mnuExcluir);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Pedido"));

        lblNome.setText("Nome");

        lblAcai.setText("Açai");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Frutas"));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        cbxMorango.setText("Morango");
        jPanel3.add(cbxMorango, new java.awt.GridBagConstraints());

        cbxBanana.setText("Banana");
        jPanel3.add(cbxBanana, new java.awt.GridBagConstraints());

        cbxCereja.setText("Cereja");
        jPanel3.add(cbxCereja, new java.awt.GridBagConstraints());

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        cmbAcai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAcaiActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cobertura"));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        cbxLeiteCondensado.setText("Leite Condensado");
        jPanel5.add(cbxLeiteCondensado, new java.awt.GridBagConstraints());

        cbxCoberturaMorango.setText("Morango");
        jPanel5.add(cbxCoberturaMorango, new java.awt.GridBagConstraints());

        cbxCoberturaChocolate.setText("Chocolate");
        jPanel5.add(cbxCoberturaChocolate, new java.awt.GridBagConstraints());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Complemento"));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        cbxLeitePo.setText("Leite em Pó");
        jPanel6.add(cbxLeitePo, new java.awt.GridBagConstraints());

        cbxPacoca.setText("Paçoca");
        jPanel6.add(cbxPacoca, new java.awt.GridBagConstraints());

        cbxChocoball.setText("Chocoball");
        jPanel6.add(cbxChocoball, new java.awt.GridBagConstraints());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrega"));
        jPanel4.setLayout(new java.awt.BorderLayout());

        grpEntrega.add(rbtnSim);
        rbtnSim.setMnemonic('S');
        rbtnSim.setSelected(true);
        rbtnSim.setText("Sim");
        jPanel4.add(rbtnSim, java.awt.BorderLayout.CENTER);

        grpEntrega.add(rbtnNao);
        rbtnNao.setMnemonic('N');
        rbtnNao.setText("Não");
        jPanel4.add(rbtnNao, java.awt.BorderLayout.PAGE_END);

        txtPreço.setText("0.00");
        txtPreço.setToolTipText("");

        jLabel4.setText("Qtd");

        spnQtd.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        lblTamanho.setText("Tamanho");

        btnExcluirPedido.setText("Excluir");
        btnExcluirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPedidoActionPerformed(evt);
            }
        });

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAcai)
                            .addComponent(lblNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome)
                            .addComponent(cmbAcai, 0, 146, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPesquisar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTamanho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTamanho, 0, 278, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInserir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPreço, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExcluirPedido)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTamanho)
                                .addComponent(cmbTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAcai)
                                .addComponent(cmbAcai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(spnQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtPreço, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNovo)
                            .addComponent(btnInserir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluirPedido))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Pedidos"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Açai", "Quantidade", "Tamanho", "Morango", "Banana", "Cereja", "Leite Condensado", "Cobertura de Morango", "Cobertura de Chocolate", "Leite em Pó", "Paçoca", "Chocoball", "Entrega", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPedidos.setComponentPopupMenu(mnuPopUp);
        jScrollPane1.setViewportView(tblPedidos);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPedidoActionPerformed
        // TODO add your handling code here:
        int linha = tblPedidos.getSelectedRow();
        if (linha >= 0) {
            if (JOptionPane.showConfirmDialog(this, "Deseja excluir esse pedido?") == JOptionPane.YES_OPTION) {
                TamanhoAcai tamanhoAcai = gerenciadorInterfaceGrafica.getGerenciadorDominio().buscarTamanhoAcaiPorAcaiETamanho((Acai) cmbAcai.getSelectedItem(), (Tamanho) cmbTamanho.getSelectedItem());
                Double valor = tamanhoAcai.getValor();
                int qtd = Integer.parseInt(spnQtd.getValue().toString());
                txtPreço.setText(String.valueOf(Double.parseDouble(txtPreço.getText()) - (valor * qtd)));
                ((DefaultTableModel) tblPedidos.getModel()).removeRow(linha);
            }
        }
    }//GEN-LAST:event_btnExcluirPedidoActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        if (validarCampos()) {
            String nome = txtNome.getText();
            Acai acai = (Acai) cmbAcai.getSelectedItem();
            int qtd = Integer.parseInt(spnQtd.getValue().toString());
            Tamanho tamanho = (Tamanho) cmbTamanho.getSelectedItem();
            String morango = null;
            String banana = null;
            String cereja = null;
            String leiteCondensado = null;
            String coberturaMorango = null;
            String coberturaChocolate = null;
            String leitePo = null;
            String pacoca = null;
            String chocoball = null;
            char entrega;
            Double valor;

            morango = selecionado(cbxMorango, morango);
            banana = selecionado(cbxBanana, banana);
            cereja = selecionado(cbxCereja, cereja);
            leiteCondensado = selecionado(cbxLeiteCondensado, leiteCondensado);
            coberturaMorango = selecionado(cbxCoberturaMorango, coberturaMorango);
            coberturaChocolate = selecionado(cbxCoberturaChocolate, coberturaChocolate);
            leitePo = selecionado(cbxLeitePo, leitePo);
            pacoca = selecionado(cbxPacoca, pacoca);
            chocoball = selecionado(cbxChocoball, chocoball);

            if (grpEntrega.getSelection().getMnemonic() == 'S') {
                entrega = 'S';
            } else {
                entrega = 'N';
            }

            TamanhoAcai tamanhoAcai = gerenciadorInterfaceGrafica.getGerenciadorDominio().buscarTamanhoAcaiPorAcaiETamanho((Acai) cmbAcai.getSelectedItem(), (Tamanho) cmbTamanho.getSelectedItem());
            valor = tamanhoAcai.getValor();

            txtPreço.setText(String.valueOf(Double.parseDouble(txtPreço.getText()) + (valor * qtd)));
            adicionarTabela(nome, acai, qtd, tamanho, morango, banana, cereja, leiteCondensado, coberturaMorango, coberturaChocolate, leitePo, pacoca, chocoball, entrega, valor);
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        gerenciadorInterfaceGrafica.carregarCombo(cmbAcai, Acai.class);
        gerenciadorInterfaceGrafica.carregarComboTamanho(cmbTamanho, (Acai) cmbAcai.getSelectedItem());
    }//GEN-LAST:event_formComponentShown

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        limparCampos();
        clienteSelecionado = gerenciadorInterfaceGrafica.abrirJanelaPesquisarCliente();
        if (clienteSelecionado != null) {
            txtNome.setText(clienteSelecionado.getNome());
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:
        if (clienteSelecionado != null && tblPedidos.getRowCount() > 0) {
            try {
                char entrega = (char) grpEntrega.getSelection().getMnemonic();
                int id = gerenciadorInterfaceGrafica.getGerenciadorDominio().inserirPedido(clienteSelecionado, entrega, Double.parseDouble(txtPreço.getText()), tblPedidos);

                JOptionPane.showMessageDialog(this, "Pedido " + id + " inserido com sucesso!");

                limparCampos();
            } catch (HibernateException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao inserir pedido.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um cliente.");
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void cmbAcaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAcaiActionPerformed
        // TODO add your handling code here:
        gerenciadorInterfaceGrafica.carregarComboTamanho(cmbTamanho, (Acai) cmbAcai.getSelectedItem());
    }//GEN-LAST:event_cmbAcaiActionPerformed

    private String selecionado(JCheckBox cbx, String texto) {
        if (cbx.isSelected()) {
            texto = "Sim";
        } else {
            texto = "Não";
        }
        return texto;
    }

    private boolean validarCampos() {
        String msgErro = "";
        FuncoesUteis.voltarCor(lblNome);
        FuncoesUteis.voltarCor(lblAcai);
        FuncoesUteis.voltarCor(lblTamanho);

        if (txtNome.getText().isEmpty()) {
            msgErro = msgErro + "Selecione um CLIENTE.\n";
            lblNome.setForeground(Color.red);
        }

        if (cmbAcai == null || cmbAcai.getSelectedItem() == null) {
            msgErro = msgErro + "Selecione um AÇAI.\n";
            lblAcai.setForeground(Color.red);
        }

        if (cmbTamanho == null || cmbTamanho.getSelectedItem() == null) {
            msgErro = msgErro + "Selecione um Tamanho.\n";
            lblTamanho.setForeground(Color.red);
        }

        if (msgErro.isEmpty()) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, msgErro, "Cadastro de Pedidos", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private void limparCampos() {
        clienteSelecionado = null;
        txtNome.setText("");
        gerenciadorInterfaceGrafica.carregarCombo(cmbAcai, Acai.class);
        gerenciadorInterfaceGrafica.carregarComboTamanho(cmbTamanho, (Acai) cmbAcai.getSelectedItem());
        spnQtd.setValue(1);
        cbxBanana.setSelected(false);
        cbxCereja.setSelected(false);
        cbxChocoball.setSelected(false);
        cbxCoberturaChocolate.setSelected(false);
        cbxCoberturaMorango.setSelected(false);
        cbxLeiteCondensado.setSelected(false);
        cbxLeitePo.setSelected(false);
        cbxMorango.setSelected(false);
        cbxPacoca.setSelected(false);
        rbtnSim.setSelected(true);
        txtPreço.setText("0.00");
        limparTabela();
    }

    private void limparTabela() {
        //Criar uma linha me branco
        ((DefaultTableModel) tblPedidos.getModel()).setRowCount(0);
    }

    private void adicionarTabela(String nome, Acai acai, int qtd, Tamanho tamanho, String morango, String banana, String cereja, String leiteCondensado, String coberturaMorango, String coberturaChocolate, String leitePo, String pacoca, String chocoball, char entrega, Double valor) {
        //Criar uma linha me branco
        ((DefaultTableModel) tblPedidos.getModel()).addRow(new Object[15]);
        int linha = tblPedidos.getRowCount() - 1;
        int coluna = 0;

        tblPedidos.setValueAt(nome, linha, coluna++);
        tblPedidos.setValueAt(acai, linha, coluna++);
        tblPedidos.setValueAt(String.valueOf(qtd), linha, coluna++);
        tblPedidos.setValueAt(tamanho, linha, coluna++);
        tblPedidos.setValueAt(morango, linha, coluna++);
        tblPedidos.setValueAt(banana, linha, coluna++);
        tblPedidos.setValueAt(cereja, linha, coluna++);
        tblPedidos.setValueAt(leiteCondensado, linha, coluna++);
        tblPedidos.setValueAt(coberturaMorango, linha, coluna++);
        tblPedidos.setValueAt(coberturaChocolate, linha, coluna++);
        tblPedidos.setValueAt(leitePo, linha, coluna++);
        tblPedidos.setValueAt(pacoca, linha, coluna++);
        tblPedidos.setValueAt(chocoball, linha, coluna++);
        tblPedidos.setValueAt(String.valueOf(entrega), linha, coluna++);
        tblPedidos.setValueAt(String.valueOf(valor), linha, coluna++);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirPedido;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JCheckBox cbxBanana;
    private javax.swing.JCheckBox cbxCereja;
    private javax.swing.JCheckBox cbxChocoball;
    private javax.swing.JCheckBox cbxCoberturaChocolate;
    private javax.swing.JCheckBox cbxCoberturaMorango;
    private javax.swing.JCheckBox cbxLeiteCondensado;
    private javax.swing.JCheckBox cbxLeitePo;
    private javax.swing.JCheckBox cbxMorango;
    private javax.swing.JCheckBox cbxPacoca;
    private javax.swing.JComboBox<String> cmbAcai;
    private javax.swing.JComboBox<String> cmbTamanho;
    private javax.swing.ButtonGroup grpEntrega;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAcai;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTamanho;
    private javax.swing.JMenuItem mnuAlterar;
    private javax.swing.JMenuItem mnuExcluir;
    private javax.swing.JMenuItem mnuInserir;
    private javax.swing.JPopupMenu mnuPopUp;
    private javax.swing.JRadioButton rbtnNao;
    private javax.swing.JRadioButton rbtnSim;
    private javax.swing.JSpinner spnQtd;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField txtNome;
    private javax.swing.JLabel txtPreço;
    // End of variables declaration//GEN-END:variables
}
