/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaces;

import gerenciador.FuncoesUteis;
import gerenciador.GerenciadorInterfaceGrafica;
import java.awt.Color;
import javax.swing.JOptionPane;
import modelo.Acai;
import modelo.Tamanho;
import modelo.TamanhoAcai;
import org.hibernate.HibernateException;

/**
 *
 * @author CONEXOS
 */
public class CadastroAcai extends javax.swing.JDialog {

    private GerenciadorInterfaceGrafica gerenciadorInterfaceGrafica;
    private Acai acaiSelecionado;
    private Tamanho tamanhoSelecionado;
    private TamanhoAcai tamanhoAcaiSelecionado;

    /**
     * Creates new form CadastroAcai
     *
     * @param parent
     * @param modal
     * @param gerenciadoInterfaceGrafica
     */
    public CadastroAcai(java.awt.Frame parent, boolean modal, GerenciadorInterfaceGrafica gerenciadoInterfaceGrafica) {
        super(parent, modal);
        this.gerenciadorInterfaceGrafica = gerenciadoInterfaceGrafica;
        acaiSelecionado = null;
        tamanhoSelecionado = null;
        tamanhoAcaiSelecionado = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblTamanho = new javax.swing.JLabel();
        cmbTamanho = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAcai = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Açai"));

        lblNome.setText("Nome");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        lblValor.setText("Valor");

        lblTamanho.setText("Tamanho");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTamanho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtValor)
                    .addComponent(cmbTamanho, 0, 196, Short.MAX_VALUE)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTamanho)
                    .addComponent(cmbTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Açai"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        tblAcai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tamanho", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAcai);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnInserir.setMnemonic('I');
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnInserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(33, 33, 33))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnCancelar))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limparCampos();
        acaiSelecionado = null;
        tamanhoSelecionado = null;
        tamanhoAcaiSelecionado = null;
        nomeBotao();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:
        if (validarCampos()) {
            String nome = txtNome.getText();
            String tamanho = cmbTamanho.getSelectedItem().toString();
            Double valor = Double.parseDouble(txtValor.getText());

            try {
                //INSERIR no banco
                if (acaiSelecionado == null) {
                    int id = gerenciadorInterfaceGrafica.getGerenciadorDominio().inserirAcai(nome, tamanho, valor);

                    JOptionPane.showMessageDialog(this, "Açaí " + id + " inserido com sucesso!");
                } else {
                    gerenciadorInterfaceGrafica.getGerenciadorDominio().alterarAcai(tamanhoAcaiSelecionado, acaiSelecionado, nome, tamanho, valor);

                    JOptionPane.showMessageDialog(this, "Açaí " + acaiSelecionado.getId() + " alterado com sucesso!");
                }
                gerenciadorInterfaceGrafica.carregarTabelaAcai(tblAcai, TamanhoAcai.class);
                limparCampos();
                nomeBotao();
            } catch (HibernateException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao inserir/alterar açaí: " + ex.getMessage());
            } catch (RuntimeException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao inserir/alterar açaí: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        limparCampos();
        tamanhoAcaiSelecionado = gerenciadorInterfaceGrafica.abrirJanelaPesquisarAcai();
        if (tamanhoAcaiSelecionado != null) {
            acaiSelecionado = tamanhoAcaiSelecionado.getAcai();
            tamanhoSelecionado = tamanhoAcaiSelecionado.getTamanho();
            preencherCampos();
        }
        FuncoesUteis.limparTabela(tblAcai);
        gerenciadorInterfaceGrafica.carregarCombo(cmbTamanho, Tamanho.class);
        gerenciadorInterfaceGrafica.carregarTabelaAcai(tblAcai, TamanhoAcai.class);
        nomeBotao();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        FuncoesUteis.limparTabela(tblAcai);
        gerenciadorInterfaceGrafica.carregarCombo(cmbTamanho, Tamanho.class);
        gerenciadorInterfaceGrafica.carregarTabelaAcai(tblAcai, TamanhoAcai.class);
        nomeBotao();
    }//GEN-LAST:event_formComponentShown

    private void carregar() {
        FuncoesUteis.limparTabela(tblAcai);
        gerenciadorInterfaceGrafica.carregarCombo(cmbTamanho, Tamanho.class);
        gerenciadorInterfaceGrafica.carregarTabelaAcai(tblAcai, TamanhoAcai.class);
        nomeBotao();
    }

    private boolean validarCampos() {
        String msgErro = "";
        FuncoesUteis.voltarCor(lblNome);
        FuncoesUteis.voltarCor(lblValor);

        if (txtNome.getText().isEmpty()) {
            msgErro = msgErro + "Digite o NOME.\n";
            lblNome.setForeground(Color.red);
        }

        if (txtValor.getText().isEmpty()) {
            msgErro = msgErro + "Digite o VALOR.\n";
            lblValor.setForeground(Color.red);
        }

        if (txtValor.getText().isEmpty()) {
            msgErro = msgErro + "Digite o VALOR.\n";
            lblValor.setForeground(Color.red);
        } else {
            try {
                Double.parseDouble(txtValor.getText());
            } catch (NumberFormatException e) {
                msgErro = msgErro + "Digite um VALOR válido.\n";
                lblValor.setForeground(Color.red);
            }
        }

        if (msgErro.isEmpty()) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, msgErro, "Cadastro de Açai", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private void preencherCampos() {
        txtNome.setText(acaiSelecionado.getNome());
        cmbTamanho.setSelectedItem(tamanhoSelecionado);
        txtValor.setText(String.valueOf(tamanhoAcaiSelecionado.getValor()));
    }

    private void nomeBotao() {
        if (acaiSelecionado == null) {
            btnInserir.setText("Inserir");
        } else {
            btnInserir.setText("Alterar");
        }
    }

    private void limparCampos() {
        acaiSelecionado = null;
        tamanhoSelecionado = null;
        tamanhoAcaiSelecionado = null;
        txtNome.setText("");
        txtValor.setText("");
        cmbTamanho.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cmbTamanho;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTamanho;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTable tblAcai;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
