DROP TABLE IF EXISTS CONSULTA;
DROP TABLE IF EXISTS PACIENTE;
DROP TABLE IF EXISTS MEDICO;
--------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE PACIENTE(
	IDPACIENTE SERIAL PRIMARY KEY,
	NOMEPACIENTE VARCHAR(30) UNIQUE,
	CIDADE VARCHAR(30) NOT NULL DEFAULT 'BAIXO GUANDU',
	ESTADO VARCHAR(2) NOT NULL DEFAULT 'ES'
);

CREATE TABLE MEDICO(
	IDMEDICO SERIAL PRIMARY KEY,
	NOMEMEDICO VARCHAR(30) UNIQUE,
	COMISSAO FLOAT DEFAULT 0.1 CHECK (COMISSAO >= 0 OR COMISSAO <= 0.3)
);

CREATE TABLE CONSULTA(
	IDCONSULTA SERIAL PRIMARY KEY,
	DATA DATE,
	HORA TIME,
	IDPACIENTE INTEGER DEFAULT 1 REFERENCES PACIENTE(IDPACIENTE) ON DELETE SET DEFAULT,
	IDMEDICO INTEGER REFERENCES MEDICO(IDMEDICO)
);
--------------------------------------------------------------------------------------------------------------------------------
INSERT INTO PACIENTE (NOMEPACIENTE, CIDADE, ESTADO) 
VALUES ('GUSTAVO NUNES', 'COLATINA', 'ES'), ('ISABELLA CORREA', DEFAULT, DEFAULT), ('LAYLA SANTOS', 'AIMORES', 'MG'),
('EDSON LIMA', 'COLATINA', DEFAULT), ('FERNANDO MARTINS', 'RIO DE JANEIRO', 'RJ');

INSERT INTO MEDICO (NOMEMEDICO, COMISSAO)
VALUES ('IGOR PULINI', DEFAULT), ('MIKAEL BOTASSI', 0.2), ('GUSTAVO NUNES', 0.3), 
('GABRIEL LUPPI', 0.15), ('MATEUS PADOVAN', 0.25);

INSERT INTO CONSULTA (DATA, HORA, IDPACIENTE, IDMEDICO)
VALUES ('2021-11-29', '15:00:00', 1, 5), ('2021-11-29', '14:00:00', 2, 3), ('2021-11-29', '13:00:00', 3, 1),
('2021-11-27', '09:00:00', 4, 5), ('2021-11-27', '10:00:00', 5, 4), ('2021-11-25', '11:00:00', 5, 1),
('2021-11-25', '18:00:00', 3, 2), ('2021-11-26', '17:00:00', 4, 4), ('2021-11-26', '08:00:00', 2, 4),
('2021-11-28', '19:00:00', 1, 1);
--------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE ESPECIALIDADE(
	IDESPECIALIDADE SERIAL PRIMARY KEY,
	ESPECIALIDADE VARCHAR(30),
	VALOR FLOAT
);

ALTER TABLE MEDICO ADD COLUMN IDESPECIALIDADE INTEGER REFERENCES ESPECIALIDADE(IDESPECIALIDADE) ON DELETE CASCADE;
ALTER TABLE CONSULTA DROP COLUMN IDMEDICO;
ALTER TABLE CONSULTA ADD COLUMN IDMEDICO INTEGER REFERENCES MEDICO(IDMEDICO) ON DELETE CASCADE;
--------------------------------------------------------------------------------------------------------------------------------
INSERT INTO ESPECIALIDADE (ESPECIALIDADE) VALUES ('CARDIOLOGIA'), ('PEDIATRIA'), ('PSIQUIATRIA'), ('UROLOGIA'), ('ECOCARDIOGRAFIA');

UPDATE MEDICO SET IDESPECIALIDADE = 1 WHERE IDMEDICO = 1;
UPDATE MEDICO SET IDESPECIALIDADE = 1 WHERE IDMEDICO = 1;




