
import javax.swing.ButtonModel;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author CONEXOS
 */
public class Telas extends javax.swing.JFrame {

    /**
     * Creates new form Telas
     */
    public Telas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpSistema = new javax.swing.ButtonGroup();
        popMenu = new javax.swing.JPopupMenu();
        itemCadastar = new javax.swing.JMenuItem();
        itemLimpar = new javax.swing.JMenuItem();
        itemEditar = new javax.swing.JMenuItem();
        bgpProcessador = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbxCidade = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        rbtWindows = new javax.swing.JRadioButton();
        rbtLinux = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cbxVersao = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstRAM = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        rbtAMD = new javax.swing.JRadioButton();
        rbtIntel = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        cbx500GB = new javax.swing.JCheckBox();
        cbx1TB = new javax.swing.JCheckBox();
        cbx320GB = new javax.swing.JCheckBox();
        btnCadastrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbRelatorio = new javax.swing.JTable();

        itemCadastar.setText("Cadastrar");
        itemCadastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        popMenu.add(itemCadastar);

        itemLimpar.setText("Limpar");
        itemLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLimparActionPerformed(evt);
            }
        });
        popMenu.add(itemLimpar);

        itemEditar.setText("Editar");
        itemEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarActionPerformed(evt);
            }
        });
        popMenu.add(itemEditar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("Cidade");

        cbxCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aracruz", "Colatina", "Serra", "Vitória" }));
        cbxCidade.setSelectedIndex(1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sist. Operacional"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        bgpSistema.add(rbtWindows);
        rbtWindows.setMnemonic('W');
        rbtWindows.setText("Windows");
        rbtWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtWindowsActionPerformed(evt);
            }
        });
        jPanel1.add(rbtWindows, java.awt.BorderLayout.CENTER);

        bgpSistema.add(rbtLinux);
        rbtLinux.setMnemonic('L');
        rbtLinux.setText("Linux");
        rbtLinux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtLinuxActionPerformed(evt);
            }
        });
        jPanel1.add(rbtLinux, java.awt.BorderLayout.PAGE_END);

        jLabel3.setText("Versão");

        jLabel4.setText("Memória RAM");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lstRAM.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Menos que 1 GB", "1 GB", "2 GB", "3 GB", "4 GB", "Mais que 4 GB" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstRAM);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Processador"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        bgpProcessador.add(rbtAMD);
        rbtAMD.setText("AMD");
        jPanel2.add(rbtAMD, java.awt.BorderLayout.CENTER);

        bgpProcessador.add(rbtIntel);
        rbtIntel.setMnemonic('I');
        rbtIntel.setText("Intel");
        jPanel2.add(rbtIntel, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("HD"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        cbx500GB.setSelected(true);
        cbx500GB.setText("500 GB");
        jPanel3.add(cbx500GB, java.awt.BorderLayout.CENTER);

        cbx1TB.setText("1 TB");
        jPanel3.add(cbx1TB, java.awt.BorderLayout.PAGE_END);

        cbx320GB.setText("320 GB");
        jPanel3.add(cbx320GB, java.awt.BorderLayout.PAGE_START);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel5.setText("Relatório");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.BorderLayout());

        tbRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cidade", "SO", "Versão", "Processador", "HD", "Memória"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbRelatorio.setComponentPopupMenu(popMenu);
        jScrollPane2.setViewportView(tbRelatorio);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cbxVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(btnCadastrar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(cbxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxVersao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtLinuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtLinuxActionPerformed
        cbxVersao.removeAllItems();
        cbxVersao.addItem("Ubuntu");
        cbxVersao.addItem("Fedora");
        cbxVersao.addItem("Red Hat");
        cbxVersao.addItem("Suse");
        cbxVersao.addItem("Debian");
        cbxVersao.setSelectedIndex(0);
    }//GEN-LAST:event_rbtLinuxActionPerformed

    private void rbtWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtWindowsActionPerformed
        cbxVersao.removeAllItems();
        cbxVersao.addItem("XP");
        cbxVersao.addItem("Win7");
        cbxVersao.addItem("Win8");
        cbxVersao.addItem("2003 Server");
        cbxVersao.addItem("2008 Server");
        cbxVersao.setSelectedIndex(2);
    }//GEN-LAST:event_rbtWindowsActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String nome = txtNome.getText();
        String cidade = cbxCidade.getSelectedItem().toString();
        String SO;
        String versao = cbxVersao.getSelectedItem().toString();
        String processador;
        String hd;
        String memoria = lstRAM.getSelectedValue();

        if (bgpSistema.getSelection().getMnemonic() == 'W') {
            SO = "Windows";
        } else {
            SO = "Linux";
        }

        if (bgpProcessador.getSelection().getMnemonic() == 'I') {
            processador = "Intel";
        } else {
            processador = "AMD";
        }

        if (cbx320GB.isSelected()) {
            hd = "320 GB";
            inserirTabela(nome, cidade, SO, versao, processador, hd, memoria);
        }
        if (cbx500GB.isSelected()) {
            hd = "500 GB";
            inserirTabela(nome, cidade, SO, versao, processador, hd, memoria);
        }
        if (cbx1TB.isSelected()) {
            hd = "1 TB";
            inserirTabela(nome, cidade, SO, versao, processador, hd, memoria);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void itemEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarActionPerformed
        int linha = tbRelatorio.getSelectedRow();
        int col = 0;
                
        txtNome.setText(tbRelatorio.getValueAt(linha, col++).toString());
        cbxCidade.setSelectedItem(tbRelatorio.getValueAt(linha, col++));

        if ((tbRelatorio.getValueAt(linha, col++).toString()).equals("Windows")) {
            bgpProcessador.setSelected((ButtonModel) rbtWindows, true);
            bgpProcessador.setSelected((ButtonModel) rbtLinux, false);
        } else {
            bgpProcessador.setSelected((ButtonModel) rbtLinux, true);
            bgpProcessador.setSelected((ButtonModel) rbtWindows, false);
        }
        
        cbxVersao.setSelectedItem(tbRelatorio.getValueAt(linha, col++));
        
        if ((tbRelatorio.getValueAt(linha, col++).toString()).equals("Intel")) {
            bgpProcessador.setSelected((ButtonModel) rbtIntel, true);
            bgpProcessador.setSelected((ButtonModel) rbtAMD, false);
        } else {
            bgpProcessador.setSelected((ButtonModel) rbtAMD, true);
            bgpProcessador.setSelected((ButtonModel) rbtIntel, false);
        }
         
        switch (tbRelatorio.getValueAt(linha, col++).toString()) {
            case "320 HD":
                cbx320GB.setSelected(true);
                cbx500GB.setSelected(false);
                cbx1TB.setSelected(false);
                break;
            case "500 HD":
                cbx320GB.setSelected(false);
                cbx500GB.setSelected(true);
                cbx1TB.setSelected(false);
                break;
            default:
                cbx320GB.setSelected(false);
                cbx500GB.setSelected(false);
                cbx1TB.setSelected(true);
                break;
        }
        
        lstRAM.setSelectedValue(tbRelatorio.getValueAt(linha, col++), true);
    }//GEN-LAST:event_itemEditarActionPerformed

    private void itemLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLimparActionPerformed
        int linha = tbRelatorio.getSelectedRow();
        ((DefaultTableModel) tbRelatorio.getModel()).removeRow(linha);
    }//GEN-LAST:event_itemLimparActionPerformed

    public void inserirTabela(String nome, String cidade, String SO, String versao, String processador, String hd, String memoria) {
        ((DefaultTableModel) tbRelatorio.getModel()).addRow(new Object[7]);
        int linha = tbRelatorio.getRowCount() - 1;
        int col = 0;
        tbRelatorio.setValueAt(nome, linha, col++);
        tbRelatorio.setValueAt(cidade, linha, col++);
        tbRelatorio.setValueAt(SO, linha, col++);
        tbRelatorio.setValueAt(versao, linha, col++);
        tbRelatorio.setValueAt(processador, linha, col++);
        tbRelatorio.setValueAt(hd, linha, col++);
        tbRelatorio.setValueAt(memoria, linha, col++);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgpProcessador;
    private javax.swing.ButtonGroup bgpSistema;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JCheckBox cbx1TB;
    private javax.swing.JCheckBox cbx320GB;
    private javax.swing.JCheckBox cbx500GB;
    private javax.swing.JComboBox<String> cbxCidade;
    private javax.swing.JComboBox<String> cbxVersao;
    private javax.swing.JMenuItem itemCadastar;
    private javax.swing.JMenuItem itemEditar;
    private javax.swing.JMenuItem itemLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstRAM;
    private javax.swing.JPopupMenu popMenu;
    private javax.swing.JRadioButton rbtAMD;
    private javax.swing.JRadioButton rbtIntel;
    private javax.swing.JRadioButton rbtLinux;
    private javax.swing.JRadioButton rbtWindows;
    private javax.swing.JTable tbRelatorio;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
